/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './welcome.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './welcome.component';
const styles_WelcomeComponent:any[] = [i0.styles];
export const RenderType_WelcomeComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_WelcomeComponent,data:{}});
export function View_WelcomeComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  welcome works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_WelcomeComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-welcome',
      ([] as any[]),(null as any),(null as any),(null as any),View_WelcomeComponent_0,
      RenderType_WelcomeComponent)),i1.ɵdid(1,114688,(null as any),0,i2.WelcomeComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const WelcomeComponentNgFactory:i1.ComponentFactory<i2.WelcomeComponent> = i1.ɵccf('app-welcome',
    i2.WelcomeComponent,View_WelcomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVVQxOC9EZXNrdG9wL1Byb2plY3RzL3Rlc3Rlci1mbG93L3NyYy9hcHAvd2VsY29tZS93ZWxjb21lLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9VVDE4L0Rlc2t0b3AvUHJvamVjdHMvdGVzdGVyLWZsb3cvc3JjL2FwcC93ZWxjb21lL3dlbGNvbWUuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvVVQxOC9EZXNrdG9wL1Byb2plY3RzL3Rlc3Rlci1mbG93L3NyYy9hcHAvd2VsY29tZS93ZWxjb21lLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvVVQxOC9EZXNrdG9wL1Byb2plY3RzL3Rlc3Rlci1mbG93L3NyYy9hcHAvd2VsY29tZS93ZWxjb21lLmNvbXBvbmVudC50cy5XZWxjb21lQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIHdlbGNvbWUgd29ya3MhXG48L3A+XG4iLCI8YXBwLXdlbGNvbWU+PC9hcHAtd2VsY29tZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLDZDQUVDO01BQUE7OztvQkNGSjtNQUFBO2lDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
